/**
 * Created by Masha Kereb on 10-Dec-16.
 */

import java.util.Properties;

public class Mail extends javax.swing.JFrame {

    /**
     * Creates new form EmailUI
     */
    public Mail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_Exit = new javax.swing.JButton();
        tab_Panel = new javax.swing.JTabbedPane();
        panel_Inbox = new javax.swing.JPanel();
        lbl_TopicIn = new java.awt.Label();
        lbl_sender = new java.awt.Label();
        tb_MainMessageIn = new javax.swing.JTextArea();
        lbl_MessageIn = new java.awt.Label();
        tb_sender = new javax.swing.JTextField();
        cb_Topic = new javax.swing.JComboBox<>();
        bt_refresh = new javax.swing.JButton();
        panel_Send = new javax.swing.JPanel();
        lbl_Topic = new java.awt.Label();
        lbl_recepient = new java.awt.Label();
        bt_Send = new javax.swing.JButton();
        tb_MainMessage = new javax.swing.JTextArea();
        tb_Topic = new javax.swing.JTextField();
        lbl_Message = new java.awt.Label();
        tb_recepient = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Messanger alpha 0.00.0.0.2.04.20.0.0.1");
        setLocation(new java.awt.Point(400, 200));
        setResizable(false);

        bt_Exit.setText("exit");
        bt_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ExitActionPerformed(evt);
            }
        });

        lbl_TopicIn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_TopicIn.setText("Topic:");

        lbl_sender.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_sender.setText("Sender");

        tb_MainMessageIn.setColumns(20);
        tb_MainMessageIn.setRows(5);

        lbl_MessageIn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_MessageIn.setText("Message:");

        cb_Topic.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_TopicItemStateChanged(evt);
            }
        });

        bt_refresh.setText("Refresh");
        bt_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_InboxLayout = new javax.swing.GroupLayout(panel_Inbox);
        panel_Inbox.setLayout(panel_InboxLayout);
        panel_InboxLayout.setHorizontalGroup(
                panel_InboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_InboxLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_refresh)
                                .addContainerGap())
                        .addGroup(panel_InboxLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(cb_Topic, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(347, Short.MAX_VALUE))
                        .addGroup(panel_InboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panel_InboxLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(panel_InboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(panel_InboxLayout.createSequentialGroup()
                                                        .addComponent(lbl_TopicIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(290, 290, 290)
                                                        .addComponent(lbl_sender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(panel_InboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lbl_MessageIn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_InboxLayout.createSequentialGroup()
                                                                .addGap(447, 447, 447)
                                                                .addComponent(tb_sender, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addComponent(tb_MainMessageIn, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panel_InboxLayout.setVerticalGroup(
                panel_InboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel_InboxLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cb_Topic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_refresh)
                                .addContainerGap(417, Short.MAX_VALUE))
                        .addGroup(panel_InboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panel_InboxLayout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addGroup(panel_InboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(panel_InboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lbl_TopicIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lbl_sender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(tb_sender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(19, 19, 19)
                                        .addComponent(lbl_MessageIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tb_MainMessageIn, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                        .addContainerGap()))
        );

        tab_Panel.addTab("Inbox", panel_Inbox);

        lbl_Topic.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_Topic.setText("Topic:");

        lbl_recepient.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_recepient.setText("Recipient:");

        bt_Send.setText("Send");
        bt_Send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_SendActionPerformed(evt);
            }
        });

        tb_MainMessage.setColumns(20);
        tb_MainMessage.setRows(5);

        lbl_Message.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_Message.setText("Message:");

        javax.swing.GroupLayout panel_SendLayout = new javax.swing.GroupLayout(panel_Send);
        panel_Send.setLayout(panel_SendLayout);
        panel_SendLayout.setHorizontalGroup(
                panel_SendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel_SendLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbl_Message, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(602, Short.MAX_VALUE))
                        .addGroup(panel_SendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panel_SendLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(panel_SendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(panel_SendLayout.createSequentialGroup()
                                                        .addComponent(lbl_Topic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(tb_Topic, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lbl_recepient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(panel_SendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(bt_Send)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_SendLayout.createSequentialGroup()
                                                                .addGap(447, 447, 447)
                                                                .addComponent(tb_recepient, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addComponent(tb_MainMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panel_SendLayout.setVerticalGroup(
                panel_SendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel_SendLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(lbl_Message, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(410, Short.MAX_VALUE))
                        .addGroup(panel_SendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panel_SendLayout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addGroup(panel_SendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(panel_SendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lbl_Topic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lbl_recepient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(tb_recepient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(tb_Topic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bt_Send)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tb_MainMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap()))
        );

        tab_Panel.addTab("Send", panel_Send);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tab_Panel)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(bt_Exit)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tab_Panel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_Exit)
                                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("Messenger alpha 0.00.0.0.2.04.20.0.0.1");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Exit Button
    private void bt_ExitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bt_ExitActionPerformed
    {//GEN-HEADEREND:event_bt_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bt_ExitActionPerformed

    // Send mail button
    private void bt_SendActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bt_SendActionPerformed
    {//GEN-HEADEREND:event_bt_SendActionPerformed
        MailActions ma = new MailActions();
        ma.sendMail(this.getPropertiesToSend());
    }//GEN-LAST:event_bt_SendActionPerformed

    // Data to send
    private Properties getPropertiesToSend() {
        String messageFormat = this.tb_MainMessage.getText();
        messageFormat = messageFormat.replaceAll("\n", "<br>");

        Properties props = new Properties();
        props.put("recipient", this.tb_recepient.getText());
        props.put("subject", this.tb_Topic.getText());
        props.put("message", messageFormat);

        return props;
    }

    // Get messages
    Properties[] props;

    private void bt_refreshActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bt_refreshActionPerformed
    {//GEN-HEADEREND:event_bt_refreshActionPerformed
        MailActions ma = new MailActions();

        props = ma.checkMail();
        for (Properties prop : props) {
            this.cb_Topic.addItem(prop.getProperty("topic"));
        }

        this.tb_sender.setText(props[0].getProperty("sender"));
        this.tb_MainMessageIn.setText(props[0].getProperty("message"));
    }//GEN-LAST:event_bt_refreshActionPerformed

    private void cb_TopicItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_cb_TopicItemStateChanged
    {//GEN-HEADEREND:event_cb_TopicItemStateChanged
        this.tb_sender.setText(props[this.cb_Topic.getSelectedIndex()].getProperty("sender"));
        this.tb_MainMessageIn.setText(props[this.cb_Topic.getSelectedIndex()].getProperty("message"));
    }//GEN-LAST:event_cb_TopicItemStateChanged

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(()
                ->
        {
            new Mail().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Exit;
    private javax.swing.JButton bt_Send;
    private javax.swing.JButton bt_refresh;
    private javax.swing.JComboBox<String> cb_Topic;
    private java.awt.Label lbl_Message;
    private java.awt.Label lbl_MessageIn;
    private java.awt.Label lbl_Topic;
    private java.awt.Label lbl_TopicIn;
    private java.awt.Label lbl_recepient;
    private java.awt.Label lbl_sender;
    private javax.swing.JPanel panel_Inbox;
    private javax.swing.JPanel panel_Send;
    private javax.swing.JTabbedPane tab_Panel;
    private javax.swing.JTextArea tb_MainMessage;
    private javax.swing.JTextArea tb_MainMessageIn;
    private javax.swing.JTextField tb_Topic;
    private javax.swing.JTextField tb_recepient;
    private javax.swing.JTextField tb_sender;
    // End of variables declaration//GEN-END:variables
}
